config/routes.rb
WeatherApi::Application.routes.draw do

  root :to => "trips#index"

  resources :cities
  resources :forecasts
  resources :eightcoupons
  resources :trips

end

app/models/city.rb
class City < ActiveRecord::Base
include HTTParty
require 'open-uri'
require 'json'


  acts_as_gmappable

  def gmaps4rails_address
  "#{zipcode}"
  end

  def local_deals
    HTTParty.get("http://api.8coupons.com/v1/getdeals?key=49bf9fac2c055141e65a2d9bd03064a1cd06069f59b9941403b24ea60ffcb8296bb6d954a145f830ed072500d4d213f8&zip=#{zip}&mileradius=20&limit=3&orderby=radius&categoryid=2,6")
  end

  def zip_weather
    HTTParty.get("http://api.wunderground.com/api/80c09000360316c5/geolookup/conditions/q/#{zip}.json")
  end

  def conditions
    zip_weather['current_observation']
  end

end

app/models/eightcoupon.rb
class Eightcoupon < ActiveRecord::Base

include HTTParty
require 'open-uri'
require 'json'

attr_accessible :zip

  def local_deals
    HTTParty.get("http://api.8coupons.com/v1/getdeals?key=49bf9fac2c055141e65a2d9bd03064a1cd06069f59b9941403b24ea60ffcb8296bb6d954a145f830ed072500d4d213f8&zip=#{zip}&mileradius=20&limit=3&orderby=radius&categoryid=2,6")
  end

app/models/excuse.rb
class Excuse < ActiveRecord::Base
  # attr_accessible :title, :body

  attr_accessible :cover_story

  has_many :trips
end

app/models/forecast.rb
class Forecast < ActiveRecord::Base

  include HTTParty
  require 'open-uri' #required for the do block at the bottom
  require 'json' #required for the do block at the bottom

  attr_accessible :country, :zip

  def country_name
    ::CountrySelect::COUNTRIES[country]
  end

  def weather
    HTTParty.get("http://api.wunderground.com/api/80c09000360316c5/geolookup/conditions/q/#{country}.json")
  end

  def zip_weather
    HTTParty.get("http://api.wunderground.com/api/80c09000360316c5/geolookup/conditions/q/#{zip}.json")
  end

  def conditions
    zip_weather['current_observation']
  end

  def temp_c
    zip_weather['temp_c']
  end

  def wunderground
    open('http://api.wunderground.com/api/80c09000360316c5/geolookup/conditions/q/IA/Cedar_Rapids.json') do |f|
      json_string = f.read
      parsed_json = JSON.parse(json_string)
      location = parsed_json['location']['city']
      temp_f = parsed_json['current_observation']['temp_f']
      print "Current temperature in #{location} is: #{temp_f}\n"
    end
  end
end

app/models/trip.rb
class Trip < ActiveRecord::Base

include HTTParty
require 'open-uri'
require 'json'


  attr_accessible :latitude, :longitude, :name, :state, :gmaps, :endzip, :startzip, :cover_story, :myarray

  #acts_as_gmappable

  #def gmaps4rails_address
  #  "#{name}, #{state}"
  #end

  def excuse
    myarray = ['Kevin Spacey stole my bicycle','It was not in the original specification', 'I will have to fix that at a later date','It must be because of leap year','Godzilla pulled me over in a stolen cop car','A stunt double stole my identity', 'A British chap put me inside a Chinese finger trap', 'The entire Roman empire spin kicked my collar bone',  'Princess Peach beat me into submission', 'Scrooge McDuck hid my Trapper Keeper', 'Chuck E Cheese broke into my house', 'Raiden from Mortal Kombat tried to sell me vacuum cleaners',  'Eddie Murphy put a banana inside my tail pipe', 'My fake tarantuala kept telling me knock knock jokes', 'I swerved to avoid banana peels on the roadway' ]
    cover_story = myarray[rand(myarray.length)]
    return cover_story
  end

  def local_deals
    HTTParty.get("http://api.8coupons.com/v1/getdeals?key=49bf9fac2c055141e65a2d9bd03064a1cd06069f59b9941403b24ea60ffcb8296bb6d954a145f830ed072500d4d213f8&zip=#{endzip}&mileradius=20&limit=3&orderby=radius&categoryid=2,6")
  end

  def zip_weather
    HTTParty.get("http://api.wunderground.com/api/80c09000360316c5/geolookup/conditions/q/#{endzip}.json")
  end

  def conditions
    zip_weather['current_observation']
  end
end

app/models/wunder_request.rb
class WunderRequest
  include HTTParty

  def self.temp(system = "c")
    if system == "c"
      current_observation['temp_c']
    elsif system == "f"
      current_observation['temp_f']
    else
      raise "Whaddya want, kelvin?"
    end
  end

  def self.local_deals
    HTTParty.get("http://api.8coupons.com/v1/getdeals?key=49bf9fac2c055141e65a2d9bd03064a1cd06069f59b9941403b24ea60ffcb8296bb6d954a145f830ed072500d4d213f8&zip=10001&mileradius=20&limit=1000&orderby=radius&categoryid=2,6")
  end


  def self.response
    HTTParty.get("http://api.wunderground.com/api/80c09000360316c5/geolookup/conditions/q/WA/Seattle.json")
  end

  def self.country
    country = "US"
    HTTParty.get("http://api.wunderground.com/api/80c09000360316c5/geolookup/conditions/q/#{country}.json")
  end

  def self.country_name
    ::CountrySelect::COUNTRIES[country]
  end

  def self.countryselect
    @country = Country.new(params[:country])
    HTTParty.get("http://api.wunderground.com/api/80c09000360316c5/geolookup/conditions/q/#{country}.json")
  end

  def self.current_observation
    response['current_observation']
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    #@cities = City.all
    @json = City.all.to_gmaps4rails
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(params[:city])
    if @city.save
      flash[:notice] = "City has been saved."
      redirect_to @city
    else
      #later
    end
  end

  def show
    @city = City.find(params[:id])
  end

end

app/controllers/eightcoupons_controller.rb
class EightcouponsController < ApplicationController

def index

  end

  def new
    @eightcoupon = Eightcoupon.new
  end

  def create
    @eightcoupon = Eightcoupon.new(params[:eightcoupon])
    if @eightcoupon.save
      flash[:notice] = "Deal saved."
      redirect_to @eightcoupon
    else
      #later
    end
  end

  def show
    @eightcoupon = Eightcoupon.find(params[:id])
  end

end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController

  def index
   # @json = Trip.all.to_gmaps4rails
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(params[:trip])
    if @trip.save
      flash[:notice] = "Trip saved."
      redirect_to @trip
    else
      #later
    end
  end

  def show
    @trip = Trip.find(params[:id])
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index
   # @json = Trip.all.to_gmaps4rails
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(params[:trip])
    if @trip.save
      flash[:notice] = "Trip saved."
      redirect_to @trip
    else
      #later
    end
  end

  def show
    @trip = Trip.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/eightcoupons_helper.rb
module EightcouponsHelper
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>

<h2>Enter the zip</h2>
  <p>
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode %>
  </p>


  <%= f.submit %>

<% end %>

app/views/cities/index.html.erb
<%= gmaps4rails(@json) %>

<%= link_to "New Map", new_city_path %>

app/views/cities/new.html.erb
<h2>Enter in a zipcode to Google Map it</h2>

<%= render "form" %>

app/views/eightcoupons/_form.html.erb
<%= form_for(@eightcoupon) do |f| %>

  <p>
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </p>

  <%= f.submit "New Deal" %>

<% end %>

app/views/eightcoupons/index.html.erb
<%= link_to "New Deal", new_eightcoupon_path %>

app/views/eightcoupons/new.html.erb
<h2>New Deal</h2>

<%= render "form" %>

app/views/eightcoupons/show.html.erb
<h2> Local entertainment and shopping deals by zip code</h2>

<p>
  <%= @eightcoupon.local_deals %>
</p>

<h2> Deal Title</h2>
<p>
  <%= @eightcoupon.local_deals.first %>
</p>


<h2> First Deal</h2>
<p>
  <%= @eightcoupon.local_deals.first['dealTitle'] %><br />
  <%= @eightcoupon.local_deals.first['name'] %><br />
  <%= @eightcoupon.local_deals.first['address'] %><br />
  <%= @eightcoupon.local_deals.first['city'] %><br />
</p>

app/views/forecasts/_form.html.erb
<%= form_for(@forecast) do |f| %>
  <p>
    <%= country_select("forecast", "country", nil, iso_codes: true) %>
  </p>

  <p>
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </p>

  <%= f.submit "New Forecast" %>

<% end %>

app/views/forecasts/index.html.erb
<%= link_to "New Forecast", new_forecast_path %>

app/views/forecasts/new.html.erb
<h2>New Forecast</h2>

<%= render "form" %>

app/views/forecasts/show.html.erb
<h2> Country </h2>
  <%= @forecast.country_name %>

<h2> Temp 'C</h2>
<p>
  <%= @forecast.conditions['temp_c'] %>
</p>

<h2> Temp 'F</h2>
<p>
  <%= @forecast.conditions['temp_f'] %>
</p>

<h2> Temperature</h2>
<p>
  <%= @forecast.conditions['temperature_string'] %>
</p>

<h2> Forecast </h2>
<p>
  <%= @forecast.conditions['weather'] %>
</p>


<h2> Weather by zip code</h2>
<p>
  <%= @forecast.zip_weather %>
</p>

app/views/layouts/[application].html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "WeatherApi" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
<link rel="stylesheet"type="text/css" href="application.css">
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <link href='http://fonts.googleapis.com/css?family=Bowlby+One+SC' rel='stylesheet' type='text/css'>
  </head>
  <body>

    <div class="navbar navbar-[fluid]-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">WeatherApi</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>


  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeatherApi</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag 'gmaps4rails' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="/javascripts/gmaps4rails.js" type="text/javascript"></script>


</head>
<body>

<%= yield %>
<%= yield :scripts %>


</body>
</html>

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <p>
    <%= f.label :startzip %><br />
    <%= f.text_field :startzip %>
  </p>

  <p>
    <%= f.label :endzip %><br />
    <%= f.text_field :endzip %>
  </p>

  <%= f.submit "New Trip" %>

<% end %>

app/views/trips/index.html.erb
<body background = "app/assets/images/road.jpeg">
<h1> Suggestatron </h1>

<body>Let's plan a <%= link_to "New Trip", new_trip_path %>! </body>

app/views/trips/new.html.erb
<h2>Here is your Suggestatron roadtrip</h2>

<%= render "form" %>

app/views/trips/show.html.erb
<h2> Temperature</h2>
<p>
  <%= @trip.conditions['temperature_string'] %>
</p>

<h2> Forecast </h2>
<p>
  <%= @trip.conditions['weather'] %>
</p>

<h2> Excuse </h2>
<p>
<td><%= @trip.excuse %></td>
</p>

<h2> Suggestatron Roadtrip Deal</h2>
<p>
  <%= @trip.local_deals.first['dealTitle'] %><br />
  <%= @trip.local_deals.first['name'] %><br />
  <%= @trip.local_deals.first['address'] %><br />
  <%= @trip.local_deals.first['city'] %><br />
</p>